name: 'Mobify Preview'
description: 'Deploy your GitHub PR to a Mobify environment and preview your site'
author: 'Mobify'
inputs:
  github-token:
    required: true
    description: 'Your GitHub token'
runs:
  using: 'node12'
  main: 'dist/index.js'
