name: 'Mobify Preview workflow'
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
